// src/app/work/do-androids-dream/page.tsx
import { Metadata } from "next";
import CaseStudyLayout from "@/components/CaseStudyLayout";
import { TextSection } from "@/components/CaseStudySection";
import CaseStudyGallery from "@/components/CaseStudyGallery";
import { getNextProject } from "@/lib/projects";

export const metadata: Metadata = {
  title: "Do Androids Dream — Motion Design",
  description:
    'A bold, two-color title sequence for Philip K. Dick\'s "Do Androids Dream of Electric Sheep?"',
  openGraph: {
    title: "Do Androids Dream — Motion Design — Timothy Ali",
    description:
      'A bold, two-color title sequence for Philip K. Dick\'s "Do Androids Dream of Electric Sheep?"',
    url: "https://www.timothyali.com/work/do-androids-dream",
  },
};

export default function DoAndroidsDreamPage() {
  return (
    <CaseStudyLayout
      jsonLd={{
        "@context": "https://schema.org",
        "@type": "CreativeWork",
        name: "Do Androids Dream — Motion Design",
        description:
          'A bold, two-color title sequence for Philip K. Dick\'s "Do Androids Dream of Electric Sheep?"',
        author: { "@type": "Person", name: "Timothy Ali", url: "https://www.timothyali.com" },
        dateCreated: "2023-01-01",
        url: "https://www.timothyali.com/work/do-androids-dream",
        image: "https://www.timothyali.com/images/do-androids-dream/hero.jpg",
      }}
      header={{
        title: "Do Androids Dream?",
        category: "Motion Design",
        year: "2023",
        role: "Director, Designer, Animator",
        timeline: "~45 seconds",
        tools: "After Effects, Illustrator",
        overview:
          'A title sequence for Philip K. Dick\'s "Do Androids Dream of Electric Sheep?" — the book that inspired Blade Runner. Rather than recreating the dark, rain-soaked aesthetic everyone expects, I went in the opposite direction: a stark, high-contrast yellow-and-black graphic style that feels closer to Saul Bass than Ridley Scott.',
      }}
      nextProject={getNextProject("do-androids-dream")}
    >
      {/* Copy */}
      <TextSection title="The Concept">
        <p>
          Every adaptation of Philip K. Dick&apos;s world defaults to the same
          visual language: neon, fog, rain, darkness. I wanted to ask: what does
          this story look like if you strip away the atmosphere and reduce it to
          its most graphic elements?
        </p>
        <p>
          The answer was a two-color world. Bright yellow and deep black —
          nothing else. The yellow represents the artificial, the synthetic, the
          electric. The black represents the void. Together they create a world
          that feels simultaneously stark and overwhelming. The limited palette
          forces the viewer to focus on shape, movement, and composition.
        </p>
      </TextSection>

      <TextSection title="Visual Language">
        <p>
          The sequence&apos;s central visual element is a dystopian skyline — a
          jagged silhouette of towers and industrial structures rendered as flat
          black vector shapes against the yellow sky. A lone silhouetted figure
          appears against the massive cityscape — the emotional core of the
          sequence: one person dwarfed by the built environment.
        </p>
        <p>
          Throughout the sequence, subtle chromatic aberration effects at the
          edges of vector shapes add a sense of instability and electronic
          interference. The world looks slightly misaligned, like it&apos;s being
          viewed through a synthetic lens.
        </p>
      </TextSection>

      <TextSection title="Motion & Pacing">
        <p>
          The sequence moves through three acts in under a minute. Act 1: the
          title builds word by word on a flat yellow field. Act 2: the cityscape
          enters and credits play against it. Act 3: the perspective shifts
          dramatically — pulled into the city along a converging road as the sun
          rises and beams radiate outward.
        </p>
        <p>
          The deliberately anti-Blade Runner aesthetic was a statement about
          adaptation itself: that a source material this rich deserves more than
          one visual interpretation.
        </p>
      </TextSection>

      {/* Gallery */}
      <CaseStudyGallery
        items={[
          { type: "video", src: "/videos/DO_ANDROIDS_DREAM_-_Title_Sequence.mp4", alt: "Do Androids Dream title sequence" },
        ]}
      />
    </CaseStudyLayout>
  );
}

// src/routes/work/do-androids-dream/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/Seo.svelte';
	import CaseStudy from '$lib/components/CaseStudy.svelte';
	import TextSection from '$lib/components/TextSection.svelte';
	import Gallery from '$lib/components/Gallery.svelte';
	import { getNextProject } from '$lib/projects';
	import { imageUrl } from '$lib/images';
	import { SITE_URL } from '$lib/site';

	const description =
		'A bold, two-color title sequence for Philip K. Dick\'s "Do Androids Dream of Electric Sheep?" — Saul Bass instead of Blade Runner.';
</script>

<Seo
	title="Do Androids Dream? — Motion Design"
	{description}
	ogKey="do-androids-dream"
	jsonLd={{
		'@context': 'https://schema.org',
		'@type': 'CreativeWork',
		name: 'Do Androids Dream? — Motion Design',
		description,
		author: { '@type': 'Person', name: 'Timothy Ali', url: SITE_URL },
		dateCreated: '2023-01-01',
		url: `${SITE_URL}/work/do-androids-dream`,
		image: imageUrl('/images/do-androids-dream/hero.jpg', SITE_URL)
	}}
/>

<CaseStudy
	title="Do Androids Dream?"
	category="Motion Design"
	year="2023"
	role="Director, Designer, Animator"
	timeline="~45 seconds"
	tools="After Effects, Illustrator"
	nextProject={getNextProject('do-androids-dream')}
>
	{#snippet overview()}
		<p>
			A title sequence for Philip K. Dick&rsquo;s <em>Do Androids Dream of Electric Sheep?</em> — the
			novel that inspired Blade Runner. Rather than recreating the dark, rain-soaked aesthetic everyone
			expects, I went the opposite direction: a stark, high-contrast yellow-and-black graphic style closer
			to Saul Bass than Ridley Scott.
		</p>
	{/snippet}

	<TextSection title="The Concept">
		<p>
			Every adaptation of Philip K. Dick&rsquo;s world defaults to the same visual language: neon,
			fog, rain, darkness. I wanted to ask what the story looks like with the atmosphere stripped
			away — reduced to its most graphic elements.
		</p>
		<p>
			The answer was a two-color world. Bright yellow and deep black, nothing else. The yellow is
			the artificial, the synthetic, the electric; the black is the void. Together they make a world
			that feels simultaneously stark and overwhelming, and the limited palette forces the eye onto
			what&rsquo;s left: shape, movement, composition.
		</p>
	</TextSection>

	<TextSection title="Visual Language">
		<p>
			The sequence&rsquo;s central element is a dystopian skyline — a jagged silhouette of towers
			and industrial structures rendered as flat black vector shapes against the yellow sky. Against
			that mass, a lone silhouetted figure: the emotional core of the sequence, one person dwarfed
			by the built environment.
		</p>
		<p>
			Subtle chromatic aberration flickers at the edges of the vector shapes throughout — a hint of
			electronic interference that makes the world feel slightly misaligned, like it&rsquo;s being
			viewed through a synthetic lens. It&rsquo;s the only effect in the piece, which is why it
			registers.
		</p>
	</TextSection>

	<TextSection title="Motion & Pacing">
		<p>
			Three acts in forty-five seconds. Act one: the title builds word by word on a flat yellow
			field. Act two: the cityscape enters and the credits play against it. Act three: the
			perspective breaks — pulled into the city along a converging road as the sun rises and beams
			radiate outward.
		</p>
		<p>
			The deliberately anti–Blade Runner aesthetic is itself the statement: source material this
			rich deserves more than one visual interpretation.
		</p>
	</TextSection>

	<Gallery
		items={[
			{
				type: 'video',
				src: '/videos/DO_ANDROIDS_DREAM_-_Title_Sequence.mp4',
				alt: 'Do Androids Dream title sequence'
			}
		]}
	/>
</CaseStudy>
