// src/routes/work/jade-aesthetics/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/Seo.svelte';
	import CaseStudy from '$lib/components/CaseStudy.svelte';
	import TextSection from '$lib/components/TextSection.svelte';
	import LiveEmbed from '$lib/components/LiveEmbed.svelte';
	import ResultsList from '$lib/components/ResultsList.svelte';
	import { getNextProject } from '$lib/projects';
	import { SITE_URL } from '$lib/site';

	const description =
		'Two complete websites for a premium medical spa in Wheaton, IL — a Framer launch site, then a 30+ page SEO-architected Next.js application. One design language, two builds.';
</script>

<Seo
	title="Jade Aesthetics — Web Design & Development"
	{description}
	ogKey="jade-aesthetics"
	jsonLd={{
		'@context': 'https://schema.org',
		'@type': 'CreativeWork',
		name: 'Jade Aesthetics — Web Design & Development',
		description,
		author: { '@type': 'Person', name: 'Timothy Ali', url: SITE_URL },
		dateCreated: '2025-01-01',
		url: `${SITE_URL}/work/jade-aesthetics`
	}}
/>

<CaseStudy
	title="Jade Aesthetics"
	category="Web Design & Development"
	year="2025–2026"
	role="Designer & Developer"
	timeline="~4 months (two phases)"
	tools="Framer (V1), Next.js, Tailwind CSS, Vercel, Claude Code (V2)"
	nextProject={getNextProject('jade-aesthetics')}
>
	{#snippet overview()}
		<p class="mb-4">
			Jade Aesthetics is a premium medical spa in Wheaton, Illinois — facials, injectables, body
			contouring, and wellness treatments. I built their entire web presence twice. The first
			version was a Framer site that launched the brand online, with a visual identity I developed
			from nothing but an existing logo. When the business outgrew the platform, I rebuilt
			everything as a server-rendered Next.js application: 30+ pages, structured data on every
			route, and a content architecture designed for long-term SEO growth.
		</p>
		<ul class="space-y-2">
			<li>— Full digital design language, developed from a single logo mark</li>
			<li>— V1: Framer launch site</li>
			<li>— V2: 30+ page Next.js application, SEO-first architecture</li>
		</ul>
	{/snippet}

	<TextSection title="Version One — Launch">
		<p>
			The practice came to me with a logo and nothing else. I developed the entire digital design
			language around it — jade greens, warm golds, cream backgrounds, and the Dream Avenue serif —
			to carry the warmth and clinical trust of the physical space onto a screen. The goal was for a
			visitor to feel the quality of the treatment rooms before reading a single word.
		</p>
		<p>
			Built in Framer, V1 did exactly what a launch site should: it gave the brand a polished home,
			a clear picture of the services and philosophy, and a fast path from zero to live.
		</p>
	</TextSection>

	<TextSection title="The Ceiling">
		<p>
			Framer was the right tool to launch on and the wrong one to grow on. No semantic HTML meant
			screen readers and search engines struggled to parse the content; no structured data, no
			sitemap control, and minimal indexable copy left Google almost nothing to rank. For a local
			med spa competing in DuPage County on high-intent searches like &ldquo;Botox Wheaton
			IL,&rdquo; that invisibility had a price measured in bookings.
		</p>
		<p>
			The content model was the other wall. Jade offers dozens of individual treatments, and each
			one deserves its own optimized page — its own entry point from search. A visual editor
			isn&rsquo;t built for that kind of scale. The business needed an architecture where one
			service means one page, indefinitely.
		</p>
	</TextSection>

	<TextSection title="Version Two — Built to Be Found">
		<p>
			I rebuilt the site as a Next.js application — App Router, Tailwind CSS, server-side rendering
			throughout, so every page delivers full HTML with no client-side dependency for content. The
			architecture is SEO-first: unique metadata on every route, JSON-LD structured data
			(MedicalBusiness, MedicalProcedure, FAQPage), auto-generated sitemaps, and breadcrumb
			navigation with schema markup.
		</p>
		<p>
			The site ships over 30 pages: a content-rich homepage, four service category pages, 16
			individual treatment pages, product pages for two skincare lines, team bios, FAQ, financing,
			blog infrastructure, and contact. Every treatment page follows one template — what it is, who
			it&rsquo;s for, what to expect, results and recovery, localized FAQs — so each procedure gives
			Google rich, indexable content and gives a nervous first-time patient real answers.
		</p>
	</TextSection>

	<TextSection title="One Language, Two Systems">
		<p>
			Nothing visual was thrown away in the rebuild — the design language survived the platform.
			What changed is how it&rsquo;s enforced. Page-level decisions made by hand in Framer became a
			component system in Next.js: service cards, FAQ accordions, testimonial carousels, and CTA
			blocks built once and reused everywhere, with consistent spacing and hierarchy baked in. The
			identity I created on day one now lives in an architecture that keeps it consistent across 30+
			pages and whatever the practice adds next.
		</p>
	</TextSection>

	<TextSection title="Process">
		<p>
			V2 was built almost entirely with Claude Code. I directed the design decisions, content
			strategy, and architecture; Claude handled implementation at speed — scaffolding the
			application, generating the SEO infrastructure, writing schemas, and templating content across
			30+ pages. Work that reads like weeks of templating compressed into days, without ceding a
			single design decision.
		</p>
	</TextSection>

	<LiveEmbed
		label="Live Site"
		description="The current Jade Aesthetics website — V2, built on Next.js. Browse the full service catalog, team page, and SEO-optimized content architecture."
		href="https://www.jadeaesthetics.co/"
		src="https://www.jadeaesthetics.co/"
		title="Jade Aesthetics Website — Version Two"
	/>

	<ResultsList
		items={[
			'Two complete websites designed and built from scratch for a single client',
			'30+ pages of SEO-optimized content across services, products, and blog infrastructure',
			'Perfect 100 Lighthouse accessibility score',
			'Structured data (JSON-LD) on every route — MedicalBusiness, MedicalProcedure, FAQPage, and BreadcrumbList schemas',
			'Server-rendered Next.js application with zero client-side content dependencies',
			'URL redirect strategy preserving all search equity through the V1-to-V2 migration',
			'V2 built and launched in approximately 2 months using Claude Code'
		]}
	/>

	<TextSection title="Outcome">
		<p>
			Jade Aesthetics now has a website built to the same standard as the experience inside the
			treatment rooms. Every procedure has its own optimized page — its own front door from Google —
			and the server-rendered infrastructure means the site is fast, accessible, and compounding
			organic traffic over time. Two builds, one vision.
		</p>
	</TextSection>
</CaseStudy>

// src/app/work/jade-aesthetics/page.tsx
import { Metadata } from "next";
import CaseStudyLayout from "@/components/CaseStudyLayout";
import { TextSection, ResultsList, LiveEmbed } from "@/components/CaseStudySection";
import { getNextProject } from "@/lib/projects";

export const metadata: Metadata = {
  title: "Jade Aesthetics — Web Design & Development",
  description:
    "Two complete websites designed and built from scratch for a premium medical spa in Wheaton, IL — from Framer launch site to SEO-architected Next.js application with 30+ pages.",
  openGraph: {
    title: "Jade Aesthetics — Web Design & Development — Timothy Ali",
    description:
      "Two complete websites designed and built from scratch for a premium medical spa in Wheaton, IL — from Framer launch site to SEO-architected Next.js application with 30+ pages.",
    url: "https://www.timothyali.com/work/jade-aesthetics",
  },
};

export default function JadeAestheticsPage() {
  return (
    <CaseStudyLayout
      jsonLd={{
        "@context": "https://schema.org",
        "@type": "CreativeWork",
        name: "Jade Aesthetics — Web Design & Development",
        description:
          "Two complete websites designed and built from scratch for a premium medical spa in Wheaton, IL — from Framer launch site to SEO-architected Next.js application with 30+ pages.",
        author: {
          "@type": "Person",
          name: "Timothy Ali",
          url: "https://www.timothyali.com",
        },
        dateCreated: "2025-01-01",
        url: "https://www.timothyali.com/work/jade-aesthetics",
      }}
      header={{
        title: "Jade Aesthetics",
        category: "Web Design & Development",
        year: "2025–2026",
        role: "Designer & Developer",
        timeline: "~4 months (two phases)",
        tools: "Framer (V1), Next.js, Tailwind CSS, Vercel, Claude Code (V2)",
        overview:
          "Jade Aesthetics is a premium medical spa in Wheaton, Illinois offering facials, injectables, body contouring, and wellness treatments. I designed and built their entire web presence from scratch — twice. The first version was a Framer site I created to launch the brand online, developing the full visual identity from only an existing logo. When the business outgrew the platform, I rebuilt everything as a server-rendered Next.js application with 30+ pages, structured data on every route, and a content architecture designed for long-term SEO growth. Two complete builds, one continuous design vision.",
      }}
      nextProject={getNextProject("jade-aesthetics")}
    >
      <TextSection title="Version One">
        <p>
          I designed and built the original Jade Aesthetics website on Framer
          from scratch. Starting with only the existing logo mark, I developed
          the entire digital design language — jade greens, warm golds, cream
          backgrounds, and the Dream Avenue serif typeface — to match the
          warmth and sophistication of the physical space. Every color choice,
          layout decision, and typographic pairing was made to communicate
          luxury and clinical trust before a visitor reads a single word.
        </p>
        <p>
          The V1 site gave Jade Aesthetics a polished digital presence that
          reflected the quality of the in-person experience. It served its
          purpose well as a launch platform — establishing the brand online
          and giving potential clients a clear picture of the services,
          philosophy, and aesthetic that define the practice.
        </p>
      </TextSection>

      <TextSection title="Why the Rebuild">
        <p>
          Framer was the right tool for getting the site live, but as the
          business grew, the platform became the bottleneck. No semantic HTML
          meant screen readers and search engines struggled to parse the
          content. No structured data, no sitemap control, and minimal
          indexable body copy left Google with almost nothing to work with.
          For a local medical spa competing in DuPage County on high-intent
          queries like &ldquo;Botox Wheaton IL&rdquo; or &ldquo;med spa near
          me,&rdquo; that invisibility was costing the business real traffic.
        </p>
        <p>
          The content model was also a constraint. Jade Aesthetics offers
          dozens of individual treatments across multiple categories — each
          one deserving its own optimized page. Framer&apos;s visual editor
          wasn&apos;t built for content-heavy sites with that many routes. The
          business needed an architecture that could scale: one service, one
          page, one entry point from search.
        </p>
      </TextSection>

      <TextSection title="Version Two">
        <p>
          I rebuilt the site from scratch as a Next.js application using the
          App Router, Tailwind CSS, and server-side rendering throughout.
          Every page delivers full HTML to the browser — no client-side
          rendering dependency for content. The architecture was designed
          SEO-first: unique metadata on every route, JSON-LD structured data
          (MedicalBusiness, MedicalProcedure, FAQPage schemas), auto-generated
          sitemaps, and breadcrumb navigation with schema markup.
        </p>
        <p>
          The site ships over 30 pages: a content-rich homepage, four service
          category pages, 16 individual treatment pages, product pages for two
          skincare lines, an about page with team bios, FAQ, financing, blog
          infrastructure, and a contact page. Every service page follows a
          consistent template — what the treatment is, who it&apos;s for, what
          to expect, results and recovery, and localized FAQs — giving Google
          rich, indexable content for each procedure.
        </p>
      </TextSection>

      <TextSection title="Design Language">
        <p>
          I designed Jade Aesthetics&apos; entire digital visual language from
          scratch. The jade green and warm gold palette, cream backgrounds,
          Dream Avenue typeface, and the interplay of photography with clean
          negative space — all of it was developed for V1 to translate the
          feel of the physical store into a digital experience. The only
          element I inherited was the logo mark. Everything else was original.
        </p>
        <p>
          V2 carries that same design language forward, but systematized for
          scale. What started as page-level decisions in Framer became a
          component-based design system in Next.js — service cards, FAQ
          accordions, testimonial carousels, and CTA blocks, all built as
          reusable pieces with consistent spacing and hierarchy. The visual
          identity I created on day one now lives in an architecture designed
          to maintain that consistency across 30+ pages and growing.
        </p>
      </TextSection>

      <TextSection title="AI-Assisted Development">
        <p>
          Version two was built almost entirely with Claude Code —
          Anthropic&apos;s agentic coding tool. I used it to scaffold the
          Next.js application, generate the SEO infrastructure, write
          structured data schemas, build reusable components, and handle the
          content architecture across 30+ pages. The workflow was
          collaborative: I directed the design decisions, content strategy,
          and architecture while Claude handled the implementation at speed.
          What would have been weeks of templating and content entry
          compressed into days.
        </p>
      </TextSection>

      <LiveEmbed
        label="Live Site"
        description="The current Jade Aesthetics website — V2, built on Next.js. Browse the full service catalog, team page, and SEO-optimized content architecture."
        href="https://www.jadeaesthetics.co/"
        src="https://www.jadeaesthetics.co/"
        title="Jade Aesthetics Website — Version Two"
      />

      <ResultsList
        items={[
          "Two complete websites designed and built from scratch for a single client",
          "30+ pages of SEO-optimized content across services, products, and blog infrastructure",
          "Perfect 100 Lighthouse accessibility score",
          "Structured data (JSON-LD) on every route — MedicalBusiness, MedicalProcedure, FAQPage, and BreadcrumbList schemas",
          "Server-rendered Next.js application with zero client-side content dependencies",
          "URL redirect strategy preserving all search equity through the V1-to-V2 platform migration",
          "V2 built and launched in approximately 2 months using Claude Code for AI-assisted development",
        ]}
      />

      <TextSection title="Outcome">
        <p>
          Jade Aesthetics now has a website built to the same standard as the
          experience inside the treatment rooms. The content architecture
          gives every procedure its own optimized page — each one a potential
          entry point from Google for someone searching for that specific
          treatment in the Wheaton area. The design language I created from
          day one now lives in a system built to scale with the business, and
          the server-rendered infrastructure means the site is fast,
          accessible, and compounding organic traffic over time. Two builds,
          one vision, zero compromises.
        </p>
      </TextSection>
    </CaseStudyLayout>
  );
}
