// src/app/contact/page.tsx
"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { transition, delay } from "@/lib/motion";

export default function ContactPage() {
  return (
    <div className="page-wrapper">
      {/* Header row */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={transition.normal}
        className="grid grid-cols-1 md:grid-cols-12 border-b border-[var(--color-border)] pb-row mb-section"
      >
        <p className="label-swiss md:col-span-3">Contact</p>
      </motion.div>

      {/* Intro */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ ...transition.normal, delay: delay.stagger }}
        className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-0 mb-section"
      >
        <div className="md:col-span-5 md:col-start-1">
          <h1
            className="heading-swiss text-headline"
          >
            Get in touch
          </h1>
        </div>
        <div className="md:col-span-5 md:col-start-7">
          <p className="leading-body">
            I&apos;m open to full-time product and brand design roles, as well as
            freelance projects. Let&apos;s talk.
          </p>
        </div>
      </motion.div>


      {/* GitHub */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ ...transition.normal, delay: delay.hero }}
      >
        <Link
          href="https://github.com/tasyusef"
          target="_blank"
          rel="noopener noreferrer"
          className="grid grid-cols-1 md:grid-cols-12 border-t border-[var(--color-border)] py-row hover-swiss gap-2 md:gap-0"
        >
          <p className="label-swiss md:col-span-3">GitHub</p>
          <p className="md:col-span-5 md:col-start-7">
            github.com/tasyusef
          </p>
        </Link>
      </motion.div>

      {/* LinkedIn */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ ...transition.normal, delay: delay.hero + delay.stagger }}
      >
        <Link
          href="https://linkedin.com/in/timothyali"
          target="_blank"
          rel="noopener noreferrer"
          className="grid grid-cols-1 md:grid-cols-12 border-t border-[var(--color-border)] py-row hover-swiss gap-2 md:gap-0"
        >
          <p className="label-swiss md:col-span-3">LinkedIn</p>
          <p className="md:col-span-5 md:col-start-7">
            linkedin.com/in/timothyali
          </p>
        </Link>
      </motion.div>

      {/* X */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ ...transition.normal, delay: delay.hero + delay.stagger * 2 }}
      >
        <Link
          href="https://x.com/twocakeS__"
          target="_blank"
          rel="noopener noreferrer"
          className="grid grid-cols-1 md:grid-cols-12 border-t border-[var(--color-border)] py-row hover-swiss gap-2 md:gap-0"
        >
          <p className="label-swiss md:col-span-3">X</p>
          <p className="md:col-span-5 md:col-start-7">
            x.com/twocakeS__
          </p>
        </Link>
      </motion.div>

      {/* Substack */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ ...transition.normal, delay: delay.hero + delay.stagger * 3 }}
      >
        <Link
          href="https://substack.com/@timothyali"
          target="_blank"
          rel="noopener noreferrer"
          className="grid grid-cols-1 md:grid-cols-12 border-t border-[var(--color-border)] py-row hover-swiss gap-2 md:gap-0"
        >
          <p className="label-swiss md:col-span-3">Substack</p>
          <p className="md:col-span-5 md:col-start-7">
            substack.com/@timothyali
          </p>
        </Link>
      </motion.div>

      {/* Availability */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ ...transition.normal, delay: delay.hero + delay.stagger * 4 }}
      >
        <div className="grid grid-cols-1 md:grid-cols-12 border-t border-b border-[var(--color-border)] py-row gap-2 md:gap-0">
          <p className="label-swiss md:col-span-3">Availability</p>
          <p className="md:col-span-5 md:col-start-7">
            Open to new projects
          </p>
        </div>
      </motion.div>
    </div>
  );
}

// src/routes/contact/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/Seo.svelte';
	import { SOCIAL_LINKS } from '$lib/site';
</script>

<Seo
	title="Contact"
	description="Get in touch with Timothy Ali — open to full-time product and brand design roles, as well as freelance projects."
	ogKey="contact"
/>

<div class="page-wrapper">
	<!-- Header row -->
	<div
		class="entrance pb-row mb-section grid grid-cols-1 border-b border-[var(--color-border)] md:grid-cols-12"
	>
		<p class="label-swiss md:col-span-3">Contact</p>
	</div>

	<!-- Intro -->
	<div
		class="entrance mb-section grid grid-cols-1 gap-4 md:grid-cols-12 md:gap-0"
		style:--entrance-delay="100ms"
	>
		<div class="md:col-span-5 md:col-start-1">
			<h1 class="heading-swiss text-headline">Get in touch</h1>
		</div>
		<div class="md:col-span-5 md:col-start-7">
			<p class="leading-body">
				I&rsquo;m open to full-time product and brand design roles, as well as freelance projects.
				Let&rsquo;s talk.
			</p>
		</div>
	</div>

	<!-- Social links -->
	{#each SOCIAL_LINKS as link, i (link.label)}
		<div class="entrance" style:--entrance-delay="{250 + i * 100}ms">
			<a
				href={link.href}
				target="_blank"
				rel="noopener noreferrer"
				class="py-row hover-swiss grid grid-cols-1 gap-2 border-t border-[var(--color-border)] md:grid-cols-12 md:gap-0"
			>
				<p class="label-swiss md:col-span-3">{link.label}</p>
				<p class="md:col-span-5 md:col-start-7">{link.handle}</p>
			</a>
		</div>
	{/each}

	<!-- Availability -->
	<div class="entrance" style:--entrance-delay="{250 + SOCIAL_LINKS.length * 100}ms">
		<div
			class="py-row grid grid-cols-1 gap-2 border-t border-b border-[var(--color-border)] md:grid-cols-12 md:gap-0"
		>
			<p class="label-swiss md:col-span-3">Availability</p>
			<p class="md:col-span-5 md:col-start-7">Open to new projects</p>
		</div>
	</div>
</div>
