// src/routes/work/xrpcafe/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/Seo.svelte';
	import CaseStudy from '$lib/components/CaseStudy.svelte';
	import TextSection from '$lib/components/TextSection.svelte';
	import ResultsList from '$lib/components/ResultsList.svelte';
	import Gallery from '$lib/components/Gallery.svelte';
	import { getNextProject } from '$lib/projects';
	import { imageUrl } from '$lib/images';
	import { SITE_URL } from '$lib/site';

	const description =
		'Visual identity, mascot system, motion design, and marketing for the #1 NFT marketplace on the XRP Ledger — cofounded and designed from day one.';
</script>

<Seo
	title="xrp.cafe — Brand Identity & Motion Design"
	{description}
	ogKey="xrpcafe"
	jsonLd={{
		'@context': 'https://schema.org',
		'@type': 'CreativeWork',
		name: 'xrp.cafe — Brand Identity & Motion Design',
		description,
		author: { '@type': 'Person', name: 'Timothy Ali', url: SITE_URL },
		dateCreated: '2021-01-01',
		url: `${SITE_URL}/work/xrpcafe`,
		image: imageUrl('/images/xrpcafe/logo_16x9.png', SITE_URL)
	}}
/>

<CaseStudy
	title="xrp.cafe"
	category="Brand Identity & Motion Design"
	year="2021–present"
	role="Cofounder / Designer"
	tools="Illustrator, After Effects"
	heroImage="/images/xrpcafe/logo_16x9.png"
	heroVideo="/videos/CAFE_EXPLORE_CREATE_TRADE.mp4"
	heroAlt="xrp.cafe Explore Create Trade motion graphic"
	nextProject={getNextProject('xrpcafe')}
>
	{#snippet overview()}
		<p class="mb-4">
			xrp.cafe is the #1 NFT marketplace on the XRP Ledger. I cofounded it and led the brand&rsquo;s
			implementation across marketing, events, and content — extending the visual identity into
			social campaigns, motion graphics, event booths, and community touchpoints over four years and
			counting.
		</p>
		<p>
			The positioning was a deliberate contrarian bet. Crypto branding in 2021 was dark, aggressive,
			and self-serious; we went warm, friendly, and approachable instead — a cozy place for NFTs.
			That warmth became the moat.
		</p>
	{/snippet}

	<TextSection title="The Mascot System">
		<p>
			The heart of the brand is its mascot: a simple, expressive coffee mug with stick-figure limbs
			and a warm smile. What started as a logo mark grew into a full cast of characters — each with
			its own personality and accessories — that became the face of the brand on every touchpoint.
		</p>
		<p>
			A mascot system earns its keep through variety without drift. I produced new character
			variations and scenes for campaigns, seasonal moments, and community milestones — a Halloween
			pumpkin mug, a beach-BBQ mug, a Super Saiyan mug — each instantly recognizable as xrp.cafe,
			none requiring a brand guideline lookup to feel right.
		</p>
	</TextSection>

	<TextSection title="Motion Graphics">
		<p>
			The &ldquo;Explore, Create, Trade&rdquo; promo distills the entire value proposition into a
			fast-paced animated piece — kinetic typography, smooth character animation, and the
			brand&rsquo;s signature blue throughout. It was designed for the feed, not the film festival:
			vertical format, legible on a phone mid-scroll, message delivered in seconds.
		</p>
		<p>
			Around the hero promo I built a library of motion assets — product launches, feature
			announcements, event recaps — that gave the brand a consistent, energetic presence in feeds.
			Each piece had the same job: communicate a platform feature in seconds, in character.
		</p>
	</TextSection>

	<TextSection title="Community as a Channel">
		<p>
			NFT marketplaces live and die by their communities, so the brand&rsquo;s primary medium was
			the daily feed. I produced a continuous stream of content for Twitter/X, Instagram, and
			Discord — product announcements, feature launches, community events, seasonal posts,
			partnerships, milestone celebrations. The cadence was relentless: multiple posts a week, each
			needing custom graphics, copy, and a read on what the community actually cared about that day.
		</p>
		<p>
			The same system extended into the physical world — booth designs, backdrops, banners, and
			merch for Consensus, Permissionless, and ETH Denver — where a warm, recognizable brand stood
			out on a conference floor full of black-and-neon.
		</p>
	</TextSection>

	<ResultsList
		items={[
			'#1 NFT marketplace on the XRP Ledger by secondary sales volume',
			'11,800+ secondary sales in a single 30-day period at peak (Nov 2023)',
			'Top 3 XRPL NFT marketplaces controlled 80%+ of all on-chain NFT volume',
			'Featured on the official XRPL developer blog',
			'Profiled by Messari as one of the most established touchpoints on XRPL',
			'XRPL Accelerator backed — institutional support from the network',
			'Consensus 2023 & 2024 — booth presence at the largest crypto conference',
			'Permissionless 2024 — booth within the Ripple X section',
			'ETH Denver — attended annually since 2022'
		]}
	/>

	<Gallery
		items={[
			{ type: 'image', src: '/images/xrpcafe/logo_16x9.png', alt: 'xrp.cafe logo' },
			{
				type: 'video',
				src: '/videos/CAFE_EXPLORE_CREATE_TRADE.mp4',
				alt: 'Explore Create Trade motion graphic'
			},
			{ type: 'image', src: '/images/xrpcafe/1.png', alt: 'Super Saiyan mug character' },
			{ type: 'image', src: '/images/xrpcafe/2.png', alt: 'Marketplace UI with characters' },
			{ type: 'image', src: '/images/xrpcafe/3.png', alt: 'BBQ beach mug character' },
			{ type: 'image', src: '/images/xrpcafe/7.png', alt: 'Halloween pumpkin mug' },
			{ type: 'image', src: '/images/xrpcafe/6.png', alt: 'JUST MINT NFTs graphic' },
			{ type: 'image', src: '/images/xrpcafe/4.png', alt: 'Jeopardy event' },
			{ type: 'image', src: '/images/xrpcafe/5.png', alt: 'VeSea charity event' },
			{ type: 'image', src: '/images/xrpcafe/XLS20_1Y-04.png', alt: 'XLS-20 one year anniversary' },
			{
				type: 'image',
				src: '/images/xrpcafe/booth_team.jpg',
				alt: 'xrp.cafe team at Consensus booth'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/booth_setup.jpg',
				alt: 'xrp.cafe booth setup at Permissionless'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/booth_table.jpg',
				alt: 'xrp.cafe booth table with stickers and merch'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/booth_tablet.jpg',
				alt: 'xrp.cafe website demo at Consensus 2023'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/event_nft_display.jpg',
				alt: 'Team at NFT event with display wall'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/xrpl_group.jpg',
				alt: 'XRP Ledger community group photo at Consensus'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/backdrop_mockup.png',
				alt: 'xrp.cafe event backdrop mockup'
			},
			{
				type: 'image',
				src: '/images/xrpcafe/banner_mockup.png',
				alt: 'xrp.cafe retractable banner mockups'
			}
		]}
	/>
</CaseStudy>

// src/app/work/xrpcafe/page.tsx
import { Metadata } from "next";
import CaseStudyLayout from "@/components/CaseStudyLayout";
import { TextSection, ResultsList } from "@/components/CaseStudySection";
import CaseStudyGallery from "@/components/CaseStudyGallery";
import { getNextProject } from "@/lib/projects";

export const metadata: Metadata = {
  title: "xrp.cafe — Brand Identity & Motion Design",
  description:
    "Visual identity, mascot system, and marketing design for the #1 NFT marketplace on the XRP Ledger.",
  openGraph: {
    title: "xrp.cafe — Brand Identity & Motion Design — Timothy Ali",
    description:
      "Visual identity, mascot system, and marketing design for the #1 NFT marketplace on the XRP Ledger.",
    url: "https://www.timothyali.com/work/xrpcafe",
  },
};

export default function XrpCafePage() {
  return (
    <CaseStudyLayout
      jsonLd={{
        "@context": "https://schema.org",
        "@type": "CreativeWork",
        name: "xrp.cafe — Brand Identity & Motion Design",
        description:
          "Visual identity, mascot system, and marketing design for the #1 NFT marketplace on the XRP Ledger.",
        author: { "@type": "Person", name: "Timothy Ali", url: "https://www.timothyali.com" },
        dateCreated: "2021-01-01",
        url: "https://www.timothyali.com/work/xrpcafe",
        image: "https://www.timothyali.com/images/xrpcafe/logo_16x9.png",
      }}
      header={{
        title: "xrp.cafe",
        category: "Brand Identity & Motion Design",
        year: "2021–present",
        role: "Cofounder / Designer",
        tools: "Illustrator, After Effects",
        overview:
          "xrp.cafe is the #1 NFT marketplace on the XRP Ledger. As cofounder and one of the designers on the team, I led the brand's implementation across marketing, events, and content — taking the visual identity and extending it into social campaigns, motion graphics, event booths, and community touchpoints. In a space dominated by dark, aggressive crypto aesthetics, we positioned xrp.cafe as warm, friendly, and approachable — a cozy place for NFTs.",
        heroImage: "/images/xrpcafe/logo_16x9.png",
        heroVideo: "/videos/CAFE_EXPLORE_CREATE_TRADE.mp4",
        heroAlt: "xrp.cafe Explore Create Trade motion graphic",
      }}
      nextProject={getNextProject("xrpcafe")}
    >
      {/* Copy */}
      <TextSection title="The Mascot System">
        <p>
          The heart of the brand is its mascot: a simple, expressive coffee mug
          character with stick-figure limbs and a warm smile. What started as a
          logo mark evolved into a full cast of characters — each with its own
          personality and accessories — that became the face of the brand across
          every touchpoint.
        </p>
        <p>
          I extended the mascot system into marketing and event materials,
          creating new character variations and scenes tailored to campaigns,
          seasonal moments, and community milestones.
        </p>
      </TextSection>

      <TextSection title="Motion Graphics">
        <p>
          The &ldquo;Explore, Create, Trade&rdquo; promo distills the entire
          xrp.cafe value proposition into a fast-paced animated piece — bold
          kinetic typography, smooth character animation, and the brand&apos;s
          signature blue palette throughout. Designed for social media: vertical
          format, instantly legible on a phone screen while scrolling.
        </p>
        <p>
          Beyond the hero promo, I produced animated content across product
          launches, feature announcements, and event recaps — building a library
          of motion assets that gave the brand a consistent, energetic presence
          in feeds. Each piece balanced speed with clarity, communicating complex
          platform features in seconds.
        </p>
      </TextSection>

      <TextSection title="Social Media & Community">
        <p>
          I produced a continuous stream of social content for Twitter/X,
          Instagram, and Discord — product announcements, feature launches,
          community events, seasonal posts, partnerships, and milestone
          celebrations. The cadence was relentless: multiple posts per week,
          each requiring custom graphics, copy, and an understanding of what
          the community actually cared about.
        </p>
        <p>
          Beyond scheduled content, I designed assets for real-time moments —
          partnership announcements, trending conversations, and community
          milestones — keeping the brand visible and responsive in a market
          that moves around the clock.
        </p>
      </TextSection>

      <ResultsList
        items={[
          "#1 NFT marketplace on the XRP Ledger by secondary sales volume",
          "11,800+ secondary sales in a single 30-day period at peak (Nov 2023)",
          "Top 3 XRPL NFT marketplaces controlled 80%+ of all on-chain NFT volume",
          "Featured on the official XRPL developer blog",
          "Profiled by Messari as one of the most established touchpoints on XRPL",
          "XRPL Accelerator backed — institutional support from the network",
          "Consensus 2023 & 2024 — booth presence at the largest crypto conference",
          "Permissionless 2024 — booth within the Ripple X section",
          "ETH Denver — attended annually since 2022",
        ]}
      />

      {/* Gallery */}
      <CaseStudyGallery
        items={[
          { type: "image", src: "/images/xrpcafe/logo_16x9.png", alt: "xrp.cafe logo" },
          { type: "video", src: "/videos/CAFE_EXPLORE_CREATE_TRADE.mp4", alt: "Explore Create Trade motion graphic" },
          { type: "image", src: "/images/xrpcafe/1.png", alt: "Super Saiyan mug character" },
          { type: "image", src: "/images/xrpcafe/2.png", alt: "Marketplace UI with characters" },
          { type: "image", src: "/images/xrpcafe/3.png", alt: "BBQ beach mug character" },
          { type: "image", src: "/images/xrpcafe/7.png", alt: "Halloween pumpkin mug" },
          { type: "image", src: "/images/xrpcafe/6.png", alt: "JUST MINT NFTs graphic" },
          { type: "image", src: "/images/xrpcafe/4.png", alt: "Jeopardy event" },
          { type: "image", src: "/images/xrpcafe/5.png", alt: "VeSea charity event" },
          { type: "image", src: "/images/xrpcafe/XLS20_1Y-04.png", alt: "XLS-20 one year anniversary" },
          { type: "image", src: "/images/xrpcafe/booth_team.jpg", alt: "xrp.cafe team at Consensus booth" },
          { type: "image", src: "/images/xrpcafe/booth_setup.jpg", alt: "xrp.cafe booth setup at Permissionless" },
          { type: "image", src: "/images/xrpcafe/booth_table.jpg", alt: "xrp.cafe booth table with stickers and merch" },
          { type: "image", src: "/images/xrpcafe/booth_tablet.jpg", alt: "xrp.cafe website demo at Consensus 2023" },
          { type: "image", src: "/images/xrpcafe/event_nft_display.jpg", alt: "Team at NFT event with display wall" },
          { type: "image", src: "/images/xrpcafe/xrpl_group.jpg", alt: "XRP Ledger community group photo at Consensus" },
          { type: "image", src: "/images/xrpcafe/backdrop_mockup.png", alt: "xrp.cafe event backdrop mockup" },
          { type: "image", src: "/images/xrpcafe/banner_mockup.png", alt: "xrp.cafe retractable banner mockups" },
        ]}
      />
    </CaseStudyLayout>
  );
}
