// src/routes/blog/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/Seo.svelte';
	import { posts, formatDate } from '$lib/posts';
</script>

<Seo
	title="Writing"
	description="Writing by Timothy Ali on design systems, AI-assisted workflows, and modernist design principles."
	ogKey="blog"
/>

<section class="page-wrapper">
	<h1 class="sr-only">Writing</h1>
	<!-- Header row -->
	<div
		class="entrance pb-row grid grid-cols-1 border-b border-[var(--color-border)] md:grid-cols-12"
	>
		<p class="label-swiss md:col-span-3" aria-hidden="true">Writing</p>
	</div>

	<!-- Posts -->
	{#each posts as post, index (post.slug)}
		<div class="entrance" style:--entrance-delay="{(index + 1) * 100}ms">
			<a
				href="/blog/{post.slug}"
				class="group hover-swiss block border-b border-[var(--color-border)]"
			>
				<div class="py-row grid grid-cols-1 gap-4 md:grid-cols-12 md:gap-0">
					<div class="md:col-span-3">
						<p class="label-swiss">{formatDate(post.date)}</p>
					</div>
					<div class="md:col-span-5 md:col-start-7">
						<h2 class="heading-swiss text-subhead">{post.title}</h2>
						<p class="leading-body text-caption-size mt-3">{post.excerpt}</p>
					</div>
				</div>
			</a>
		</div>
	{/each}
</section>

// src/app/blog/page.tsx
"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { transition, delay } from "@/lib/motion";
import { posts } from "@/lib/posts";

export default function BlogPage() {
  return (
    <section className="page-wrapper">
      <h1 className="sr-only">Writing</h1>
      {/* Header row */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={transition.normal}
        className="grid grid-cols-1 md:grid-cols-12 border-b border-[var(--color-border)] pb-row"
      >
        <p className="label-swiss md:col-span-3" aria-hidden="true">Writing</p>
      </motion.div>

      {/* Posts */}
      {posts.map((post, index) => (
        <motion.div
          key={post.slug}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ ...transition.normal, delay: delay.stagger * (index + 1) }}
        >
          <Link
            href={`/blog/${post.slug}`}
            className="group block border-b border-[var(--color-border)] hover-swiss"
          >
            <div className="grid grid-cols-1 md:grid-cols-12 py-row gap-4 md:gap-0">
              <div className="md:col-span-3">
                <p className="label-swiss">{post.date}</p>
              </div>
              <div className="md:col-span-5 md:col-start-7">
                <h2
                  className="heading-swiss text-subhead"
                >
                  {post.title}
                </h2>
                <p
                  className="mt-3 leading-body text-caption-size"
                >
                  {post.excerpt}
                </p>
              </div>
            </div>
          </Link>
        </motion.div>
      ))}
    </section>
  );
}
