// src/components/Footer.tsx
import Link from "next/link";
import { NAV_LINKS, NAV_LINK_COLUMNS } from "@/lib/layout";

export default function Footer() {
  return (
    <footer className="px-swiss pb-8">
      <div className="border-t border-[var(--color-border)] py-8">
        {/* Desktop */}
        <div className="hidden md:grid md:grid-cols-12 items-center">
          <div className="md:col-span-3">
            <p className="label-swiss text-[var(--color-foreground)]">Timothy Ali</p>
          </div>
          {NAV_LINKS.map((link, i) => (
            <Link
              key={link.href}
              href={link.href}
              className={`label-swiss hover-swiss ${NAV_LINK_COLUMNS[i]} md:col-span-1`}
            >
              {link.label}
            </Link>
          ))}
          <div className="md:col-start-12 md:col-span-1 flex justify-end">
            <span className="label-swiss">&copy; {new Date().getFullYear()}</span>
          </div>
        </div>

        {/* Mobile */}
        <div className="md:hidden flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <p className="label-swiss text-[var(--color-foreground)]">Timothy Ali</p>
            <div className="flex items-center gap-4 flex-wrap">
              {NAV_LINKS.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="label-swiss hover-swiss"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
          <div className="flex justify-end">
            <span className="label-swiss">&copy; {new Date().getFullYear()}</span>
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
	import { NAV_LINKS, NAV_LINK_COLUMNS } from '$lib/nav';

	const year = new Date().getFullYear();
</script>

<footer class="px-swiss pb-8">
	<div class="border-t border-[var(--color-border)] py-8">
		<!-- Desktop -->
		<div class="hidden items-center md:grid md:grid-cols-12">
			<div class="md:col-span-3">
				<p class="label-swiss text-[var(--color-foreground)]">Timothy Ali</p>
			</div>
			{#each NAV_LINKS as link, i (link.href)}
				<a href={link.href} class="label-swiss hover-swiss {NAV_LINK_COLUMNS[i]} md:col-span-1">
					{link.label}
				</a>
			{/each}
			<div class="flex justify-end md:col-span-1 md:col-start-12">
				<span class="label-swiss">&copy; {year}</span>
			</div>
		</div>

		<!-- Mobile -->
		<div class="flex flex-col gap-4 md:hidden">
			<div class="flex items-center justify-between">
				<p class="label-swiss text-[var(--color-foreground)]">Timothy Ali</p>
				<div class="flex flex-wrap items-center gap-4">
					{#each NAV_LINKS as link (link.href)}
						<a href={link.href} class="label-swiss hover-swiss">{link.label}</a>
					{/each}
				</div>
			</div>
			<div class="flex justify-end">
				<span class="label-swiss">&copy; {year}</span>
			</div>
		</div>
	</div>
</footer>
